# Generated by Django 2.0.6 on 2018-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismws', '0002_auto_20181010_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='', help_text='This is the fucking website, BITCH'),
        ),
    ]
