# Generated by Django 2.0.6 on 2018-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismws', '0004_remove_userprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='catatonia',
            field=models.BooleanField(default=False, help_text='Seleccionar si el estado del paciente está asociado a catatonías.', verbose_name='Catatonías'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emotional_attachments',
            field=models.BooleanField(default=False, help_text='Seleccionar si el paciente siente un fuerte apego/preocupación por objetos inusuales o si tiene intereses excesivamente circunscritos/perseverantes.', verbose_name='Apego emocional'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_factors',
            field=models.BooleanField(default=False, help_text='Seleccionar si el estado del paciente está asociado a una afección médica/genética o a un factor ambiental conocidos.', verbose_name='Factores externos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='functional_impact',
            field=models.BooleanField(default=False, help_text='Seleccionar si el conjunto de los síntomas limitan y alteran el funcionamiento diario del paciente.', verbose_name='Impacto en el funcionamiento diario'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intellectual_disabilities',
            field=models.BooleanField(default=False, help_text='Seleccionar si al paciente le ha sido diagnosticada una discapacidad intelectual.', verbose_name='Discapacidad intelectual'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='low_communicative_skills',
            field=models.BooleanField(default=False, help_text='Seleccionar si el paciente ha sufrido alteraciones/retrasos en el desarrollo del lenguaje.', verbose_name='Alteraciones en el desarrollo del lenguaje'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_diseases',
            field=models.BooleanField(default=False, help_text='Seleccionar si el estado del paciente está asociado a un trastorno del neurodesarrollo, mental o del comportamiento', verbose_name='Otros trastornos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='symptoms_since_childhood',
            field=models.BooleanField(default=True, help_text='Seleccionar si los síntomas han estado presentes desde la infancia temprana del paciente.', verbose_name='Síntomas desde la infancia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Cualquier dato relevante del paciente.', max_length=1000, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
