# Generated by Django 2.0.6 on 2018-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismws', '0005_auto_20181010_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='functional_impact',
            field=models.BooleanField(default=True, help_text='Seleccionar si el conjunto de los síntomas limitan y alteran el funcionamiento diario del paciente.', verbose_name='Impacto en el funcionamiento diario'),
        ),
    ]
