# Generated by Django 2.0.6 on 2018-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismws', '0006_auto_20181010_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='echolalias',
            field=models.BooleanField(default=False, help_text='Seleccionar si el paciente presenta tendencia a producir ecolalias.', verbose_name='Ecolalias'),
        ),
    ]
