# Generated by Django 2.0.6 on 2019-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismws', '0007_userprofile_echolalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='catatonia',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='echolalias',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emotional_attachments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='external_factors',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='functional_impact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='intellectual_disabilities',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='low_communicative_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='other_diseases',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='symptoms_since_childhood',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='q_ai_1',
            field=models.CharField(choices=[('A', 'Muchas veces al día'), ('B', 'Unas pocas veces al día'), ('C', 'Unas pocas veces a la semana'), ('D', 'Menos de una vez al mes'), ('E', 'Nunca')], default='A', help_text='Seleccionar si el niño/a es capaz de fingir mediante el juego, por ejemplo cuidar de muñecas como si fueran niños, hablar por un teléfono móvil de mentira....', max_length=1, verbose_name='¿Finge tu hijo/a al jugar?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='q_ai_2',
            field=models.CharField(choices=[('A', 'Muchas veces al día'), ('B', 'Unas pocas veces al día'), ('C', 'Unas pocas veces a la semana'), ('D', 'Menos de una vez al mes'), ('E', 'Nunca')], default='A', help_text='Seleccionar si el niño/a suele seguir la dirección de la mirada de la persona que está con él/ella.', max_length=1, verbose_name='¿Sigue tu hijo/a la dirección de tu mirada?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='q_ai_3',
            field=models.CharField(choices=[('A', 'Muy comunes'), ('B', 'Más o menos comunes'), ('C', 'Poco comunes'), ('D', 'Muy infrecuentes'), ('E', 'Mi hijo/a no habla')], default='A', help_text='Indicar la habitualidad.', max_length=1, verbose_name='Describirías sus primeras palabras como...'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='q_ai_4',
            field=models.CharField(choices=[('A', 'Muchas veces al día'), ('B', 'Unas pocas veces al día'), ('C', 'Unas pocas veces a la semana'), ('D', 'Menos de una vez al mes'), ('E', 'Nunca')], default='A', help_text='Indicar si se trata de un comportamiento frecuente.', max_length=1, verbose_name='¿Suele tu hijo mirar a la nada sin propósito aparente?'),
        ),
    ]
