# Generated by Django 2.0.6 on 2019-07-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autismws', '0008_auto_20190714_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default='12', max_length=2, verbose_name='Edad (en meses)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Género'),
        ),
    ]
