# Generated by Django 2.0.6 on 2018-07-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_sentences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentences',
            new_name='Sentence',
        ),
    ]
