# Generated by Django 2.0.6 on 2018-07-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180711_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity01',
            name='extra_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity01',
            name='transcription',
            field=models.TextField(null=True),
        ),
    ]
