# Generated by Django 2.0.6 on 2018-08-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20180730_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
