# Generated by Django 2.0.6 on 2018-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_lettervalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpanishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
