# Generated by Django 2.0.6 on 2018-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_spanishword'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity02',
            name='first_word',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_first_word',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_first_word_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_second_word',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_second_word_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity02',
            name='second_word',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='session',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity02',
            name='session_group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
