# Generated by Django 2.0.6 on 2018-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20180823_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity02',
            name='patient_first_word',
            field=models.TextField(blank=True),
        ),
    ]
