# Generated by Django 2.0.6 on 2018-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20180823_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity02',
            name='original_failed_first_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_failed_first_word_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_failed_second_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='original_failed_second_word_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='patient_failed_first_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='patient_failed_second_word',
            field=models.TextField(blank=True, null=True),
        ),
    ]
