# Generated by Django 2.0.6 on 2018-08-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20180824_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity02',
            name='original_first_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity02',
            name='original_first_word_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity02',
            name='original_second_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity02',
            name='original_second_word_points',
            field=models.IntegerField(null=True),
        ),
    ]
