# Generated by Django 2.0.6 on 2018-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20180824_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity03',
            name='answer_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='reaction_time_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='session',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity03',
            name='session_group',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity03',
            name='tone_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='total_commission_errors',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='total_commission_successes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='total_omission_errors',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='total_omission_successes',
            field=models.FloatField(null=True),
        ),
    ]
