# Generated by Django 2.0.6 on 2018-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_auto_20180927_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity04',
            name='emotion_to_show',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='main_emotion_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='reaction_time',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='session',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity04',
            name='session_group',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
