# Generated by Django 2.0.6 on 2018-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20181004_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity04',
            name='anger_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='disgust_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='fear_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='happiness_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='sadness_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='surprise_list',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
