# Generated by Django 2.0.6 on 2018-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20181006_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity04',
            name='phase',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
