# Generated by Django 2.0.6 on 2018-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_activity04_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity05',
            name='answer_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='answer_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='answer_3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='reaction_time_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='reaction_time_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='reaction_time_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='session',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity05',
            name='session_group',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity06',
            name='session',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity06',
            name='session_group',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
