# Generated by Django 2.0.6 on 2018-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_activity07'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity06',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
