# Generated by Django 2.0.6 on 2018-12-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_activity06_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity02',
            name='session',
        ),
        migrations.RemoveField(
            model_name='activity02',
            name='session_group',
        ),
        migrations.RemoveField(
            model_name='activity03',
            name='session',
        ),
        migrations.RemoveField(
            model_name='activity03',
            name='session_group',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='session',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='session_group',
        ),
        migrations.RemoveField(
            model_name='activity05',
            name='session',
        ),
        migrations.RemoveField(
            model_name='activity05',
            name='session_group',
        ),
        migrations.RemoveField(
            model_name='activity06',
            name='session',
        ),
        migrations.RemoveField(
            model_name='activity06',
            name='session_group',
        ),
        migrations.RemoveField(
            model_name='activity07',
            name='session',
        ),
        migrations.RemoveField(
            model_name='activity07',
            name='session_group',
        ),
    ]
