# Generated by Django 2.0.6 on 2018-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_auto_20181213_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettervalue',
            name='name',
            field=models.TextField(default='q', unique=True),
            preserve_default=False,
        ),
    ]
