# Generated by Django 2.0.6 on 2018-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_lettervalue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettervalue',
            name='name',
            field=models.TextField(),
        ),
    ]
