# Generated by Django 2.0.6 on 2018-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_auto_20181216_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity02',
            name='first_word_reaction_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='second_word_reaction_time',
            field=models.FloatField(null=True),
        ),
    ]
