# Generated by Django 2.0.6 on 2018-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_auto_20181216_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity02',
            name='failed_first_word_reaction_time',
            field=models.FloatField(null=True),
        ),
    ]
