# Generated by Django 2.0.6 on 2018-12-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_activity02_failed_first_word_reaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity02',
            name='failed_second_word_reaction_time',
            field=models.FloatField(null=True),
        ),
    ]
