# Generated by Django 2.0.6 on 2018-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_activity03_session_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity04',
            name='emotion_guessed',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='emotion_to_guess',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity04',
            name='reaction_time',
            field=models.FloatField(null=True),
        ),
    ]
