# Generated by Django 2.0.6 on 2018-12-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0031_auto_20181220_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity04',
            old_name='emotion_guessed',
            new_name='guessed_emotion',
        ),
    ]
