# Generated by Django 2.0.6 on 2018-12-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_auto_20181221_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity04',
            name='session_group',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
