# Generated by Django 2.0.6 on 2019-05-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_auto_20181221_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity04',
            old_name='anger_list',
            new_name='shown_emotion',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='disgust_list',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='fear_list',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='happiness_list',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='main_emotion_list',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='sadness_list',
        ),
        migrations.RemoveField(
            model_name='activity04',
            name='surprise_list',
        ),
    ]
