# Generated by Django 2.0.6 on 2019-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_auto_20190708_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity01',
            name='answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity02',
            name='answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity03',
            name='answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity04',
            name='answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity05',
            name='answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity06',
            name='answer',
            field=models.BooleanField(default=True),
        ),
    ]
